### ISSUE TITLE
Make a logo

### ISSUE THREAD

**Issue by Ybalrid** [Ybalrid/Annwvyn#184]
I need to create a real logo for this project...

**Comment by zuuritaly** [comment]
Hello @Ybalrid  
I'm a graphic designer and I design logos for open source projects. 
Usually I ask the following questions to assist me in the creative process:

Do you have something in your mind for the logo?
Do you want something specific for the logo?
What colors do you want in the logo?

With your answers I will design a logo for your project and if you like it you can keep it and used.

Best Regards

Zuur

**Comment by Ybalrid** [comment]
Hi @zuuritaly !

I'm potentially interested. let me describe more the kind of stuff that I would see as a logo for this project.

First let me explain a bit the name.
The name "Annwvyn" itself is (one of the spellings of) the name of "the other world" in old Celtic (more precisely welsh) mythology. 

It's also in reference to a really old poem in old welsh called **Preiddeu Annwfn** from a manuscript called the "Book of Taliesin".

It seems to describe a strange "adventure" of King Arthur and the knights of the round tables going to the "other world" to retrieve a magic cauldron. 

The project itself is a video game engine. So a software development framework for games (or anything interactive in 3D) that is designed to be played with a virtual reality headset...

I had vague ideas about something like a stylized knight in armor going through a portal (that would look like an oval-shaped thingy like in the "Portal" video game).

And for Colors, if the dominant one was some kind of green, I think it could be nice. 

If you have other/better ideas, don't hesitate to propose them ;-)

**Comment by zuuritaly** [comment]
Hello @Ybalrid 

Im going to design something with the knight and a portal, I think this is a great Idea.

Best regards!

Zuur

**Comment by Ybalrid** [comment]
Thanks a lot! 😄 

The project doesn't have any real graphics identity, so you can do whatever you want. 

There's also a shade of blue that is present in that website https://www.annwvyn.org/. If you think it looks neat, maybe try doing something that could integrate well with that? I don't really know... 😅

**Comment by Ybalrid** [comment]
It looks like he just vanished. 😅
